//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Snum { get; set; }
        public string Hotel { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> Depature { get; set; }
        public string Types { get; set; }
        public Nullable<int> Guest { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
